language: python
dist: bionic
sudo: true

git:
  depth: 1

cache:
  - pip
  - npm
  - yarn

addons:
  mariadb: '10.3'

matrix:
  include:
  - name: "Python 2.7 Basic Setup"
    python: 2.7
    env: TEST=bench
    script: ls

  - name: "Python 3.6 Basic Setup"
    python: 3.6
    env: TEST=bench
    script: ls

  - name: "Python 3.7 Basic Setup"
    python: 3.7
    env: TEST=bench
    script: ls

  - name: "Python 3.8 Production Setup"
    python: 3.8
    env: TEST=bench
    script: ls

  - name: "Python 2.7 Production Setup"
    python: 2.7
    env: TEST=bench
    script: ls

  - name: "Python 3.6 Production Setup"
    python: 3.6
    env: TEST=bench
    script: ls

  - name: "Python 3.7 Production Setup"
    python: 3.7
    env: TEST=bench
    script: ls

  - name: "Python 3.8 Production Setup"
    python: 3.8
    env: TEST=bench
    script: ls

  - name: "Python 2.7 Tests"
    python: 2.7
    env: TEST=bench
    script: ls

  - name: "Python 3.7 Tests"
    python: 3.7
    env: TEST=bench
    script: ls

  - name: "Python 3.5 Easy Install"
    python: 3.5
    env: TEST=easy_install
    script: ls

  - name: "Python 3.7 Easy Install"
    python: 3.7
    env: TEST=easy_install
    script: ls

  - name: "Python 3.8 Easy Install"
    python: 3.8
    env: TEST=easy_install
    script: ls
    
  - stage: release
    # Advanced: optionally overwrite your default `script` step to skip the tests
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - python setup.py bdist_wheel
        - nvm install lts/*
        - npx semantic-release
      on:
        all_branches: true

install:
  - pip install urllib3 pyOpenSSL ndg-httpsclient pyasn1

  - if [ $TEST == "bench" ];then
       wget -q -O /tmp/wkhtmltox.tar.xz https://github.com/frappe/wkhtmltopdf/raw/master/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz;
       tar -xf /tmp/wkhtmltox.tar.xz -C /tmp;
       sudo mv /tmp/wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf;
       sudo chmod o+x /usr/local/bin/wkhtmltopdf;

      mkdir -p ~/.bench;
      cp -r $TRAVIS_BUILD_DIR/* ~/.bench;
      pip install -q -U -e ~/.bench;
      sudo pip install -q -U -e ~/.bench;

      mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'";
      mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'";
      mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'";
      mysql -u root -e "FLUSH PRIVILEGES";
    fi

  - if [ $TEST == "easy_install" ];then
      mkdir -p /tmp/.bench;
      cp -r $TRAVIS_BUILD_DIR/* /tmp/.bench;
    fi
